name: Publish Gem

on:
  push:
    branches: [ release ]

jobs:
  publish:
    timeout-minutes: 10 # 6 hours (default) is too long
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.2'
        bundler-cache: true
    - name: Test
      run: bundle exec rake

    - name: Release Gem
      uses: discourse/publish-rubygems-action@v2-beta
      env:
        RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
        GIT_EMAIL: automated@jevon.org
        GIT_NAME: GitHub Actions
        RELEASE_COMMAND: rake release
