name: Publish Gem

on:
  push:
    branches: [ release ]

jobs:
  build:
    timeout-minutes: 10 # 6 hours (default) is too long
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.2'
        bundler-cache: true
    - name: Test
      run: bundle exec rake

    - name: Release Gem
      uses: cadwallion/publish-rubygems-action@master
      env:
        GITHUB_TOKEN: ${{secrets.PERSONAL_TOKEN}}
        RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
        RELEASE_COMMAND: |
          git config --global user.email "automated@jevon.org" &&
          git config --global user.name "GitHub Actions" &&
          rake release
